version: 2.1
# orbs - reusable packages for use #
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
# jobs - set of instructions / functions
jobs:
  build: #job name
    docker: #environment
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      -  image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test
  # for build-and-push
  build-and-push:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: docker build -t genkaitoppa/education-space:latest
      - run:
          name: Login to Docker Hub
          command: echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Push Docker Image
          command: docker push genkaitoppa/education-space:latest

# workflow - defines what sequence will the jobs run
workflows:
  simple_workflow: #workflow name
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test

# executor
# executor: docker/docker
